version: '3.8'
services:
  dev-db:
    image: postgres:13.2
    container_name: nest-tutorial-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    ports:
      - 5434:5432

networks:
  nest-network:
